# Generated by Django 4.0.2 on 2022-02-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ManyToManyField(to='main_app.Status'),
        ),
    ]
